export const get_routines = {
    REQUEST: "REQUEST_GET_ROUTINES",
    SUCCESS: "RECEIVE_GET_ROUTINES_SUCCESS",
    FAILURE: "RECEIVE_GET_ROUTINES_FAILURE",
}

export const create_routine = {
    REQUEST: "REQUEST_CREATE_ROUTINE",
    SUCCESS: "RECEIVE_CREATE_ROUTINE_SUCCESS",
    FAILURE: "RECEIVE_CREATE_ROUTINE_FAILURE"
}

export const delete_routine = {
    REQUEST: "REQUEST_DELETE_ROUTINE",
    SUCCESS: "RECEIVE_DELETE_ROUTINE_SUCCESS",
    FAILURE: "RECEIVE_DELETE_ROUTINE_FAILURE"
}

export const get_exercises = {
    REQUEST: "REQUEST_GET_EXERCISES",
    SUCCESS: "RECEIVE_GET_EXERCISES_SUCCESS",
    FAILURE: "RECEIVE_GET_EXERCISES_FAILURE",
}

export const create_exercise = {
    REQUEST: "REQUEST_CREATE_EXERCISE",
    SUCCESS: "RECEIVE_CREATE_EXERCISE_SUCCESS",
    FAILURE: "RECEIVE_CREATE_EXERCISE_FAILURE"
}

export const delete_exercise = {
    REQUEST: "REQUEST_DELETE_EXERCISE",
    SUCCESS: "RECEIVE_DELETE_EXERCISE_SUCCESS",
    FAILURE: "RECEIVE_DELETE_EXERCISE_FAILURE"
}

export const get_logs = {
    REQUEST: "REQUEST_GET_LOGS",
    SUCCESS: "RECEIVE_GET_LOGS_SUCCESS",
    FAILURE: "RECEIVE_GET_LOGS_FAILURE",
}

export const create_log = {
    REQUEST: "REQUEST_CREATE_LOG",
    SUCCESS: "RECEIVE_CREATE_LOG_SUCCESS",
    FAILURE: "RECEIVE_CREATE_LOG_FAILURE"
}

export const delete_log = {
    REQUEST: "REQUEST_DELETE_LOG",
    SUCCESS: "RECEIVE_DELETE_LOG_SUCCESS",
    FAILURE: "RECEIVE_DELETE_LOG_FAILURE"
}

export const CHANGE_TEXT = "CHANGE_TEXT"

export const SET_WEIGHT = "SET_WEIGHT"
export const SET_REPS = "SET_REPS"

